# To start all app containers and have them talking to each other, in the
# root folder /, run 'docker-compose up'.
# Refer to /README.md for more information.

# Docker Compose File Format Version.
version: "3.7"

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules # Required to persist node_modules between container stop/starts.
    ports:
      - 5000:5000

  client:
    build:
      context: ./client
    # This will force server service to build and start before client.
    depends_on:
      - api
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules # Required to persist node_modules between container stop/starts.
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
